feat: org belonging enforcment
Rookout/piper pull request #110
Opened 2023-07-25 02:37 UTC by gosharo

Signed-off-by: Gosha <gosha@rookout.com>

## Pull Request

### Description

Please provide a brief description of the changes made in this pull request.

### Related Issue(s)

If this pull request addresses or relates to any open issues, please mention them here using the syntax `Fixes #<issue_number>` or `Resolves #<issue_number>`.

### Checklist

Before submitting this pull request, please ensure that you have completed the following tasks:

- [ ] Reviewed the [Contributing Guidelines](../docs/CONTRIBUTING.md) for the Piper project.
- [ ] Ensured that your changes follow the [coding guidelines and style](../docs/CONTRIBUTING.md#coding-guidelines) of the project.
- [ ] Run the tests locally and made sure they pass.
- [ ] Updated the relevant documentation, if applicable.

### Testing Instructions

Please provide clear instructions on how to test and verify the changes made in this pull request.

### Additional Information

Add any additional information or context that would be helpful in understanding and reviewing this pull request.

2023-07-27 18:20 UTC, ElDuderinos requested changes

2023-07-27 18:20 UTC, ElDuderinos commented on pkg/git_provider/github.go
> +	if c.cfg.EnforceOrgBelonging && webhookPayload.OwnerID != c.cfg.OrgID {
What's the default here for the int64? Nil? 0? Check that they aren't the default

2023-07-27 18:25 UTC, gosharo commented on pkg/git_provider/github.go
> +	if c.cfg.EnforceOrgBelonging && webhookPayload.OwnerID != c.cfg.OrgID {
user.GetID() return 0 of there is no ID

2023-07-27 18:26 UTC, gosharo commented on pkg/git_provider/github.go
> +	if c.cfg.EnforceOrgBelonging && webhookPayload.OwnerID != c.cfg.OrgID {
and if the first one is false, the second not evaluated

2023-07-27 18:27 UTC, ElDuderinos commented on pkg/git_provider/github.go
> +	if c.cfg.EnforceOrgBelonging && webhookPayload.OwnerID != c.cfg.OrgID {
So if ownerid is 0 we don't want the enforcement to pasd

2023-07-27 18:31 UTC, gosharo commented on pkg/git_provider/github.go
> +	if c.cfg.EnforceOrgBelonging && webhookPayload.OwnerID != c.cfg.OrgID {
ohhh you mean webhookPayload.OwnerID...
we are getting it from the webhook payload.. and if it missing, then it could be passed.. 
what are your suggestions ?

2023-07-27 18:31 UTC, gosharo commented on pkg/git_provider/github.go
> +	if c.cfg.EnforceOrgBelonging && webhookPayload.OwnerID != c.cfg.OrgID {
we can check something like 
c.cfg.EnforceOrgBelonging && webhookPayload.OwnerID != 0 && webhookPayload.OwnerID != c.cfg.OrgID

2023-07-27 18:32 UTC, gosharo commented on pkg/git_provider/github.go
> +	if c.cfg.EnforceOrgBelonging && webhookPayload.OwnerID != c.cfg.OrgID {
but c.cfg.OrgID can't be 0 ... it will fail the init of gitProvider

2023-07-27 18:56 UTC, ElDuderinos commented on pkg/git_provider/github.go
> +	if c.cfg.EnforceOrgBelonging && webhookPayload.OwnerID != c.cfg.OrgID {
should be 
```
c.cfg.EnforceOrgBelonging && (webhookPayload.OwnerID == 0 || webhookPayload.OwnerID != c.cfg.OrgID)
```
Cause if it's 0 and you need enforcement then you can't check enforcement validity and thus fail it.

2023-07-28 04:22 UTC, gosharo commented on pkg/git_provider/github.go
> +	if c.cfg.EnforceOrgBelonging && webhookPayload.OwnerID != c.cfg.OrgID {
done

2023-08-14 05:53 UTC, ElDuderinos approved these changes

2023-09-06 10:18 UTC, merged