bitbucket cloud support
Rookout/piper pull request #120
Opened 2023-08-26 18:17 UTC by gosharo

- fix: bitbucket server support
- feat: bitbucket event handling
- fix: bitbucket server support
- fix: bitbucket server support
- fix: bitbucket server support
- trigger
- fix: debug listFiles
- fix: debug listFiles
- fix: debug listFiles
- fix: get file debug with rookout
- fix: get files debug with rookout
- fix: set status rookout debug
- fix: set status rookout debug
- fix: set status rookout debug
- feat: bitbucket build status
- fix: pull request event parsing
- fix: update

## Pull Request

### Description

Please provide a brief description of the changes made in this pull request.

### Related Issue(s)

If this pull request addresses or relates to any open issues, please mention them here using the syntax `Fixes #<issue_number>` or `Resolves #<issue_number>`.

### Checklist

Before submitting this pull request, please ensure that you have completed the following tasks:

- [ ] Reviewed the [Contributing Guidelines](../docs/CONTRIBUTING.md) for the Piper project.
- [ ] Ensured that your changes follow the [coding guidelines and style](../docs/CONTRIBUTING.md#coding-guidelines) of the project.
- [ ] Run the tests locally and made sure they pass.
- [ ] Updated the relevant documentation, if applicable.

### Testing Instructions

Please provide clear instructions on how to test and verify the changes made in this pull request.

### Additional Information

Add any additional information or context that would be helpful in understanding and reviewing this pull request.

2023-08-27 06:47 UTC, Urook commented on pkg/git_provider/bitbucket.go
> +		RepoSlug:    *repo,
Notice that repo slug may differ from repo name

2023-08-27 06:48 UTC, Urook requested changes

2023-08-27 06:48 UTC, Urook commented on pkg/git_provider/bitbucket.go
> +func (b BitbucketServerClientImpl) isRepoWebhookExists(repo string) (*bitbucket.Webhook, bool) {
```suggestion
func (b BitbucketServerClientImpl) doesRepoWebhookExist(repo string) (*bitbucket.Webhook, bool) {
```

2023-08-27 06:52 UTC, gosharo commented on pkg/git_provider/bitbucket.go
> +		RepoSlug:    *repo,
in this API, the repo slug is the repo name..

2023-08-27 06:54 UTC, gosharo commented on pkg/git_provider/bitbucket.go
> +func (b BitbucketServerClientImpl) isRepoWebhookExists(repo string) (*bitbucket.Webhook, bool) {
although it's the right way in English, for boolean methods it's a convention ..

2023-08-27 06:54 UTC, gosharo commented on pkg/git_provider/bitbucket.go
> +		RepoSlug:    *repo,
```func (r *Webhooks) Create(ro *WebhooksOptions) (*Webhook, error) {
	data, err := r.buildWebhooksBody(ro)
	if err != nil {
		return nil, err
	}
	urlStr := r.c.requestUrl("/repositories/%s/%s/hooks", ro.Owner, ro.RepoSlug)
	response, err := r.c.execute("POST", urlStr, data)
	if err != nil {
		return nil, err
	}

	return decodeWebhook(response)
}
```

2023-08-27 06:55 UTC, gosharo commented on pkg/git_provider/bitbucket.go
> +		RepoSlug:    *repo,
and at this API https://developer.atlassian.com/cloud/bitbucket/rest/api-group-repositories/#api-repositories-workspace-repo-slug-hooks-get
They use slug as repo name

2023-08-27 07:04 UTC, Urook commented on pkg/git_provider/types.go
>  	RepoName     *string
I suggest having different props for repo name and repo slug in case we ever have a repo with spacea in the name or that has capital letters, etc.

2023-08-27 07:12 UTC, gosharo commented on pkg/git_provider/types.go
>  	RepoName     *string
it webhook Uuid, auto-generated by bitbucket cloud

2023-08-27 07:13 UTC, gosharo commented on pkg/git_provider/types.go
>  	RepoName     *string
https://developer.atlassian.com/cloud/bitbucket/rest/api-group-repositories/#api-repositories-workspace-repo-slug-hooks-uid-get

2023-08-27 07:39 UTC, Urook commented on pkg/git_provider/bitbucket.go
> +		RepoSlug:    *repo,
The thing is, you have name which is the name you gave the repo, and the slug, which is the parsed name.

In many cases, they will be the same.

For example:
Name: tutorial-python
Slug: tutorial-python

However, sometimes they may differ:

Name: Tutorial Python
Slug: tutorial-python

Therefore, I recommend separating, especially if we intend for the project to be as generic as possible for more providers in the future. (GitLab for example will also benefit from a similar separation)
Although GitHub is very straight forward in that regard, some providers are better dealt with if we do stuff like prop separation

2023-08-29 09:53 UTC, Urook commented on pkg/git_provider/bitbucket.go
> +		RepoSlug:    *repo,
@gosharo are you sure it will work for repos with spaces in their name

2023-08-29 11:10 UTC, nissim-infra approved these changes
i added a comments their is also few other syntax for const and etc but looks good.
check the notes by @Urook also

2023-08-29 11:10 UTC, nissim-infra commented on pkg/git_provider/bitbucket.go
> +	case "repo:push":
@gosharo you can this package for better look code and more readable.

https://github.com/tidwall/gjson

and you basically can take a look on the kubernetes code how they access path by the label selector and etc.

2023-09-01 12:05 UTC, gosharo commented on pkg/git_provider/bitbucket.go
> +		RepoSlug:    *repo,
you are right, it doesn't work.
What are your suggestion ? add function that replaces white spaces to dashes ?

2023-09-03 07:14 UTC, Urook commented on pkg/git_provider/bitbucket.go
> +		RepoSlug:    *repo,
I suggest separqting repo name from repo slug. Maybe even add something like repo id if you want to support gitlab in the futute (in GitLab, the name and url can be whqteven you want and even have different names completely)

2023-09-03 07:17 UTC, Urook requested changes

2023-09-03 07:17 UTC, Urook commented on pkg/utils/common.go
> +	pattern := regexp.MustCompile(`[^a-zA-Z_1-9\.-]+`)
I believe bitbucket repo slugs dont have upper case letters, better test that

2023-09-03 07:18 UTC, Urook commented on pkg/git_provider/bitbucket.go
> +		RepoSlug:    *repo,
Also, regarding owner, as far as I know  Bitbucket uses shorthands for owners like ROOK (or ROK, dont remember if it is 3 or 4 chars). So there also may be differences between owner name and owner (slug?) "api name"

2023-09-04 07:36 UTC, gosharo commented on pkg/utils/common.go
> +	pattern := regexp.MustCompile(`[^a-zA-Z_1-9\.-]+`)
I have tests, it's not case sensitive

2023-09-04 07:36 UTC, gosharo commented on pkg/git_provider/bitbucket.go
> +	case "repo:push":
@nissim-infra done

2023-09-06 07:51 UTC, nissim-infra approved these changes

2023-09-06 08:49 UTC, merged