fix: json yaml conflic umarshling template ref to DAG task
Rookout/piper pull request #56
Opened 2023-06-23 07:01 UTC by gosharo

Signed-off-by: Gosha <gosha@rookout.com>

## Pull Request

### Description

Please provide a brief description of the changes made in this pull request.

### Related Issue(s)

If this pull request addresses or relates to any open issues, please mention them here using the syntax `Fixes #<issue_number>` or `Resolves #<issue_number>`.

### Checklist

Before submitting this pull request, please ensure that you have completed the following tasks:

- [ ] Reviewed the [Contributing Guidelines](../docs/CONTRIBUTING.md) for the Piper project.
- [ ] Ensured that your changes follow the [coding guidelines and style](../docs/CONTRIBUTING.md#coding-guidelines) of the project.
- [ ] Run the tests locally and made sure they pass.
- [ ] Updated the relevant documentation, if applicable.

### Testing Instructions

Please provide clear instructions on how to test and verify the changes made in this pull request.

### Additional Information

Add any additional information or context that would be helpful in understanding and reviewing this pull request.

2023-06-23 07:01 UTC, gosharo commented
/jira open task

2023-06-23 07:01 UTC, nissim-infra approved these changes

2023-06-24 17:17 UTC, qadiludmer commented on pkg/workflow_handler/workflows_utils_test.go
> +	// Test case 1: Empty file list
Add the following tests
- handling yaml with wrong fields (not matching to the DAG struct)
- handling yaml with syntax error

2023-06-24 17:18 UTC, qadiludmer requested changes
see comments

2023-06-25 03:15 UTC, gosharo commented on pkg/workflow_handler/workflows_utils_test.go
> +	// Test case 1: Empty file list
done

2023-06-27 09:29 UTC, nissim-infra approved these changes

2023-06-27 09:34 UTC, merged