feat: k8s event listener
Rookout/piper pull request #80
Opened 2023-07-01 05:58 UTC by qadiludmer

Signed-off-by: Adi Ludmer <Adi.Ludmer@qedma.com>

## Pull Request

### Description

Please provide a brief description of the changes made in this pull request.

### Related Issue(s)

If this pull request addresses or relates to any open issues, please mention them here using the syntax `Fixes #<issue_number>` or `Resolves #<issue_number>`.

### Checklist

Before submitting this pull request, please ensure that you have completed the following tasks:

- [ ] Reviewed the [Contributing Guidelines](../docs/CONTRIBUTING.md) for the Piper project.
- [ ] Ensured that your changes follow the [coding guidelines and style](../docs/CONTRIBUTING.md#coding-guidelines) of the project.
- [ ] Run the tests locally and made sure they pass.
- [ ] Updated the relevant documentation, if applicable.

### Testing Instructions

Please provide clear instructions on how to test and verify the changes made in this pull request.

### Additional Information

Add any additional information or context that would be helpful in understanding and reviewing this pull request.

2023-07-01 07:31 UTC, gosharo requested changes

2023-07-01 07:31 UTC, gosharo commented on pkg/listener/argo_events_broker.go
> +	clientset, err := kubernetes.NewForConfig(config)
we can use our existing client under globalClients.Workflows it has a k8s client

2023-07-01 07:31 UTC, gosharo commented on pkg/listener/argo_events_broker.go
> +	watcher := cache.NewListWatchFromClient(clientset.CoreV1().RESTClient(), "pods", corev1.NamespaceDefault, nil)
we are looking for Workflows

2023-07-01 07:31 UTC, gosharo commented on pkg/listener/argo_events_broker.go
> +		&corev1.Pod{},
v1alpha1.Workflow{}

2023-07-01 07:31 UTC, gosharo commented on pkg/listener/event_broker_example.go
> +type EventBrokerExample struct {
why do we need an example ?

2023-07-01 12:19 UTC, qadiludmer commented on pkg/listener/event_broker_example.go
> +type EventBrokerExample struct {
The example became the real deal 😆

2023-07-02 05:14 UTC, gosharo commented
/jira open task

2023-07-08 08:49 UTC, closed without merging